In [42]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

### 1. Loading dataset

The data used for this project come from: https://www.kaggle.com/datasets/grandmaster07/student-exam-performance-dataset-analysis

In [43]:
dataset = pd.read_csv("dataset.csv")

### 2. Data Cleaning

2.1 Check and remove duplaciates

In [44]:
dataset.duplicated().sum()

np.int64(0)

There are no duplicates in the dataset to remove.

2.2 Detect missing values

In [45]:
dataset.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

There are three features with missing values: Teacher_Quality, Parental_Education_Level and Distance_from_Home.

Since all three features are ordinal categorical variables, we will initially impute missing values using the mode.

In [ ]:
dataset["Teacher_Quality"].fillna(dataset["Teacher_Quality"].mode()[0], inplace = True)
dataset["Parental_Education_Level"].fillna(dataset["Parental_Education_Level"].mode()[0], inplace = True)
dataset["Distance_from_Home"].fillna(dataset["Distance_from_Home"].mode()[0], inplace = True)

In [47]:
dataset.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

### 3. Data Preprocessing

**3.1 Binary Encoding**

There are four binary features: Extracurricular_Activities, Internet_Access, Learning_Disabilities, Gender.

In [48]:
dataset["Extracurricular_Activities"].value_counts()

Extracurricular_Activities
Yes    3938
No     2669
Name: count, dtype: int64

In [49]:
dataset["Internet_Access"].value_counts()

Internet_Access
Yes    6108
No      499
Name: count, dtype: int64

In [50]:
dataset["Learning_Disabilities"].value_counts()

Learning_Disabilities
No     5912
Yes     695
Name: count, dtype: int64

In [51]:
dataset["Gender"].value_counts()

Gender
Male      3814
Female    2793
Name: count, dtype: int64

In [ ]:
dataset["Gender"] = dataset["Gender"].replace({"Male": 1, "Female": 0})
dataset["Extracurricular_Activities"] = dataset["Extracurricular_Activities"].replace({"Yes": 1, "No": 0})
dataset["Internet_Access"] = dataset["Internet_Access"].replace({"Yes": 1, "No": 0})
dataset["Learning_Disabilities"] = dataset["Learning_Disabilities"].replace({"Yes": 1, "No": 0})
dataset["School_Type"] = dataset["School_Type"].replace({"Public": 1, "Private": 0})

In [53]:
dataset.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,0,7,73,Low,1,0,Low,Medium,1,Positive,3,0,High School,Near,1,67
1,19,64,Low,Medium,0,8,59,Low,1,2,Medium,Medium,1,Negative,4,0,College,Moderate,0,61
2,24,98,Medium,Medium,1,7,91,Medium,1,2,Medium,Medium,1,Neutral,4,0,Postgraduate,Near,1,74
3,29,89,Low,Medium,1,8,98,Medium,1,1,Medium,Medium,1,Negative,4,0,High School,Moderate,1,71
4,19,92,Medium,Medium,1,6,65,Medium,1,3,Medium,High,1,Neutral,4,0,College,Near,0,70

**3.2 Ordinal encoding**

There are eight ordinals features: Parental_Involvement, Access_to_Resources, Motivation_Level, Family_Income, Teacher_Quality, Peer_Influence, Parental_Education_Level, Distance_from_Home

In [54]:
ordinal_features = ["Parental_Involvement", "Access_to_Resources", "Motivation_Level", "Family_Income", "Teacher_Quality", "Peer_Influence", "Parental_Education_Level", "Distance_from_Home"]

In [55]:
dataset["Distance_from_Home"].value_counts()

Distance_from_Home
Near        3951
Moderate    1998
Far          658
Name: count, dtype: int64

In [56]:
categories = [
    ["Low", "Medium", "High"],      # Parental Involvment 
    ["Low", "Medium", "High"],        # Access to Resources
    ["Low", "Medium", "High"],        # Motivation Level 
    ["Low", "Medium", "High"],        # Family Income
    ["Low", "Medium", "High"],        # Teacher Quality
    ["Positive", "Neutral", "Negative"],        # Peer Influence
    ["High School", "College", "Postgraduate"],        # Parental Education Level
    ["Near", "Moderate", "Far"]      # Distance from Home
]

In [57]:
ordinal_encoder = OrdinalEncoder(categories=categories)

In [58]:
dataset[ordinal_features] = ordinal_encoder.fit_transform(dataset[ordinal_features])

In [59]:
dataset.head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0.0,2.0,0,7,73,0.0,1,0,0.0,1.0,1,0.0,3,0,0.0,0.0,1,67
1,19,64,0.0,1.0,0,8,59,0.0,1,2,1.0,1.0,1,2.0,4,0,1.0,1.0,0,61
2,24,98,1.0,1.0,1,7,91,1.0,1,2,1.0,1.0,1,1.0,4,0,2.0,0.0,1,74
3,29,89,0.0,1.0,1,8,98,1.0,1,1,1.0,1.0,1,2.0,4,0,0.0,1.0,1,71
4,19,92,1.0,1.0,1,6,65,1.0,1,3,1.0,2.0,1,1.0,4,0,1.0,0.0,0,70
5,19,88,1.0,1.0,1,8,89,1.0,1,3,1.0,1.0,1,0.0,3,0,2.0,0.0,1,71
6,29,84,1.0,0.0,1,7,68,0.0,1,1,0.0,1.0,0,1.0,2,0,0.0,1.0,1,67
7,25,78,0.0,2.0,1,6,50,1.0,1,1,2.0,2.0,1,2.0,2,0,0.0,2.0,1,66
8,17,94,1.0,2.0,0,6,80,2.0,1,0,1.0,0.0,0,1.0,1,0,1.0,0.0,1,69
9,23,98,1.0,1.0,1,8,71,1.0,1,0,2.0,2.0,1,0.0,5,0,0.0,1.0,1,72

**3.3 Feature Scaling**

In [60]:
scaler = StandardScaler()